apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-shabo
    argocd.argoproj.io/instance: my-app
  name: nginx-shabo
  namespace: shabo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-shabo
  type: NodePort
